const mapData = new Map([
	["Area contains many Totems", {
		"nameLong": "Area contains many Totems",
		"nameShort": "ms",
		"nameMod": "Ceremonial",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["(20-30)% increased number of Rare Monsters", {
		"nameLong": "(20-30)% increased number of Rare Monsters",
		"nameShort": "nu",
		"nameMod": "Antagonist's",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by 2 additional Rogue Exiles", {
		"nameLong": "Area is inhabited by 2 additional Rogue Exiles",
		"nameShort": "gu",
		"nameMod": "Anarchic",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Skeletons", {
		"nameLong": "Area is inhabited by Skeletons",
		"nameShort": "eto",
		"nameMod": "Skeletal",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Goatmen", {
		"nameLong": "Area is inhabited by Goatmen",
		"nameShort": "oa",
		"nameMod": "Capricious",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Sea Witches and their Spawn", {
		"nameLong": "Area is inhabited by Sea Witches and their Spawn",
		"nameShort": "awn",
		"nameMod": "Slithering",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Undead", {
		"nameLong": "Area is inhabited by Undead",
		"nameShort": "ead",
		"nameMod": "Undead",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by ranged monsters", {
		"nameLong": "Area is inhabited by ranged monsters",
		"nameShort": "ged",
		"nameMod": "Emanant",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Animals", {
		"nameLong": "Area is inhabited by Animals",
		"nameShort": "ima",
		"nameMod": "Feral",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Demons", {
		"nameLong": "Area is inhabited by Demons",
		"nameShort": "emo",
		"nameMod": "Demonic",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Humanoids", {
		"nameLong": "Area is inhabited by Humanoids",
		"nameShort": "hu",
		"nameMod": "Bipedal",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Solaris fanatics", {
		"nameLong": "Area is inhabited by Solaris fanatics",
		"nameShort": "lar",
		"nameMod": "Solar",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Lunaris fanatics", {
		"nameLong": "Area is inhabited by Lunaris fanatics",
		"nameShort": "una",
		"nameMod": "Lunar",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Ghosts", {
		"nameLong": "Area is inhabited by Ghosts",
		"nameShort": "ost",
		"nameMod": "Haunting",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Cultists of Kitava", {
		"nameLong": "Area is inhabited by Cultists of Kitava",
		"nameShort": "tav",
		"nameMod": "Feasting",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has increased monster variety", {
		"nameLong": "Area has increased monster variety",
		"nameShort": "ety",
		"nameMod": "Multifarious",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area is inhabited by Abominations", {
		"nameLong": "Area is inhabited by Abominations",
		"nameShort": "omi",
		"nameMod": "Abhorrent",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters' skills Chain 2 additional times", {
		"nameLong": "Monsters' skills Chain 2 additional times",
		"nameShort": "tim",
		"nameMod": "Chaining",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters are Hexproof", {
		"nameLong": "Monsters are Hexproof",
		"nameShort": "oof",
		"nameMod": "Hexproof",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have 60% less effect of Curses on Monsters", {
		"nameLong": "Monsters have 60% less effect of Curses on Monsters",
		"nameShort": "n m",
		"nameMod": "Hexwarded",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Slaying Enemies close together can attract monsters from Beyond this realm", {
		"nameLong": "Slaying Enemies close together can attract monsters from Beyond this realm",
		"nameShort": "yi",
		"nameMod": "Otherworldly",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Area contains two Unique Bosses", {
		"nameLong": "Area contains two Unique Bosses",
		"nameShort": "tw",
		"nameMod": "Twinned",
		"packSize": 7,
		"quantity": 19,
		"rarity": 11,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have (25-30)% more Life Monsters cannot be Stunned", {
		"nameLong": "Monsters have (25-30)% more Life Monsters cannot be Stunned",
		"nameShort": "ned",
		"nameMod": "Unwavering",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters fire 2 additional Projectiles", {
		"nameLong": "Monsters fire 2 additional Projectiles",
		"nameShort": "je",
		"nameMod": "Splitting",
		"packSize": 7,
		"quantity": 19,
		"rarity": 11,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have +40% Physical Damage Reduction", {
		"nameLong": "Monsters have +40% Physical Damage Reduction",
		"nameShort": "uct",
		"nameMod": "Armoured",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have (40-49)% more Life", {
		"nameLong": "Monsters have (40-49)% more Life",
		"nameShort": "undefined",
		"nameMod": "Fecund",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have (22-25)% increased Damage", {
		"nameLong": "Monsters have (22-25)% increased Damage",
		"nameShort": "undefined",
		"nameMod": "Savage",
		"packSize": 7,
		"quantity": 19,
		"rarity": 11,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters deal (90-110)% extra Physical Damage as Fire", {
		"nameLong": "Monsters deal (90-110)% extra Physical Damage as Fire",
		"nameShort": "as fi",
		"nameMod": "Burning",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters deal (90-110)% extra Physical Damage as Cold", {
		"nameLong": "Monsters deal (90-110)% extra Physical Damage as Cold",
		"nameShort": "s col",
		"nameMod": "Freezing",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters deal (90-110)% extra Physical Damage as Lightning", {
		"nameLong": "Monsters deal (90-110)% extra Physical Damage as Lightning",
		"nameShort": "tn",
		"nameMod": "Shocking",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters deal (31-35)% extra Physical Damage as Chaos |Monsters Inflict Withered for 2 seconds on Hit", {
		"nameLong": "Monsters deal (31-35)% extra Physical Damage as Chaos |Monsters Inflict Withered for 2 seconds on Hit",
		"nameShort": "nds",
		"nameMod": "Profane",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have (25-30)% increased Movement Speed |Monsters have (35-45)% increased Attack Speed |Monsters have (25-30)% increased Cast Speed", {
		"nameLong": "Monsters have (25-30)% increased Movement Speed |Monsters have (35-45)% increased Attack Speed |Monsters have (25-30)% increased Cast Speed",
		"nameShort": "5-",
		"nameMod": "Fleet",
		"packSize": 7,
		"quantity": 19,
		"rarity": 11,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters reflect 18% of Physical Damage", {
		"nameLong": "Monsters reflect 18% of Physical Damage",
		"nameShort": "f p",
		"nameMod": "Punishing",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters reflect 18% of Elemental Damage", {
		"nameLong": "Monsters reflect 18% of Elemental Damage",
		"nameShort": "al d",
		"nameMod": "Mirrored",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Unique Boss deals 25% increased Damage |Unique Boss has 30% increased Attack and Cast Speed", {
		"nameLong": "Unique Boss deals 25% increased Damage |Unique Boss has 30% increased Attack and Cast Speed",
		"nameShort": "|u",
		"nameMod": "Overlord's",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Unique Boss has 35% increased Life Unique |Boss has 70% increased Area of Effect", {
		"nameLong": "Unique Boss has 35% increased Life Unique |Boss has 70% increased Area of Effect",
		"nameShort": "|b",
		"nameMod": "Titan's",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have a 20% chance to cause Elemental Ailments on Hit", {
		"nameLong": "Monsters have a 20% chance to cause Elemental Ailments on Hit",
		"nameShort": "cau",
		"nameMod": "Empowered",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters cannot be Taunted |Monsters' Action Speed cannot be modified to below base value", {
		"nameLong": "Monsters cannot be Taunted |Monsters' Action Speed cannot be modified to below base value",
		"nameShort": "od",
		"nameMod": "Unstoppable",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["All Monster Damage from Hits always Ignites", {
		"nameLong": "All Monster Damage from Hits always Ignites",
		"nameShort": "lw",
		"nameMod": "Conflagrating",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["+25% Monster Chaos Resistance |+40% Monster Elemental Resistances", {
		"nameLong": "+25% Monster Chaos Resistance |+40% Monster Elemental Resistances",
		"nameShort": "+2",
		"nameMod": "Resistant",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have a 50% chance to avoid Poison, Impale, and Bleeding", {
		"nameLong": "Monsters have a 50% chance to avoid Poison, Impale, and Bleeding",
		"nameShort": "n,",
		"nameMod": "Impervious",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have 60% chance to Impale with Attacks", {
		"nameLong": "Monsters have 60% chance to Impale with Attacks",
		"nameShort": "e w",
		"nameMod": "Impaling",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have +60% chance to Suppress Spell Damage", {
		"nameLong": "Monsters have +60% chance to Suppress Spell Damage",
		"nameShort": "+6",
		"nameMod": "Oppressive",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters gain (40-49)% of Maximum Life as Extra Maximum Energy Shield", {
		"nameLong": "Monsters gain (40-49)% of Maximum Life as Extra Maximum Energy Shield",
		"nameShort": "m e",
		"nameMod": "Buffered",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["Unique Bosses are Possessed", {
		"nameLong": "Unique Bosses are Possessed",
		"nameShort": "sess",
		"nameMod": "Enthralled",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "prefix",
		"danger": 0,
		"popularity": 0
	}],
	["(20-30)% more Magic Monsters", {
		"nameLong": "(20-30)% more Magic Monsters",
		"nameShort": "gi",
		"nameMod": "of Bloodlines",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters Poison on Hit", {
		"nameLong": "Monsters Poison on Hit",
		"nameShort": "on o",
		"nameMod": "of Venom",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players cannot inflict Exposure", {
		"nameLong": "Players cannot inflict Exposure",
		"nameShort": "ure",
		"nameMod": "of Balance",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have 100% increased Area of Effect", {
		"nameLong": "Monsters have 100% increased Area of Effect",
		"nameShort": "00",
		"nameMod": "of Giants",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have (360-400)% increased Critical Strike Chance |+(41-45)% to Monster Critical Strike Multiplier", {
		"nameLong": "Monsters have (360-400)% increased Critical Strike Chance |+(41-45)% to Monster Critical Strike Multiplier",
		"nameShort": "1-",
		"nameMod": "of Deadliness",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 60% less Recovery Rate of Life and Energy Shield", {
		"nameLong": "Players have 60% less Recovery Rate of Life and Energy Shield",
		"nameShort": "f l",
		"nameMod": "of Smothering",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players cannot Regenerate Life, Mana or Energy Shield", {
		"nameLong": "Players cannot Regenerate Life, Mana or Energy Shield",
		"nameShort": "shi",
		"nameMod": "of Stasis",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has patches of Burning Ground", {
		"nameLong": "Area has patches of Burning Ground",
		"nameShort": "g g",
		"nameMod": "of Flames",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has patches of Chilled Ground", {
		"nameLong": "Area has patches of Chilled Ground",
		"nameShort": "lle",
		"nameMod": "of Ice",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has patches of Shocked Ground which increase Damage taken by 50%", {
		"nameLong": "Area has patches of Shocked Ground which increase Damage taken by 50%",
		"nameShort": "wh",
		"nameMod": "of Lightning",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has patches of desecrated ground", {
		"nameLong": "Area has patches of desecrated ground",
		"nameShort": "ese",
		"nameMod": "of Desecration",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Area has patches of Consecrated Ground", {
		"nameLong": "Area has patches of Consecrated Ground",
		"nameShort": "gro",
		"nameMod": "of Consecration",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players are Cursed with Elemental Weakness", {
		"nameLong": "Players are Cursed with Elemental Weakness",
		"nameShort": "kn",
		"nameMod": "of Elemental Weakness",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players are Cursed with Vulnerability", {
		"nameLong": "Players are Cursed with Vulnerability",
		"nameShort": "ln",
		"nameMod": "of Vulnerability",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players are Cursed with Enfeeble", {
		"nameLong": "Players are Cursed with Enfeeble",
		"nameShort": "ebl",
		"nameMod": "of Enfeeblement",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players are Cursed with Temporal Chains", {
		"nameLong": "Players are Cursed with Temporal Chains",
		"nameShort": "ora",
		"nameMod": "of Temporal Chains",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["(-12--9)% maximum Player Resistances", {
		"nameLong": "(-12--9)% maximum Player Resistances",
		"nameShort": "mu",
		"nameMod": "of Exposure",
		"packSize": 7,
		"quantity": 19,
		"rarity": 11,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Cannot Leech from Monsters", {
		"nameLong": "Cannot Leech from Monsters",
		"nameShort": "m m",
		"nameMod": "of Congealment",
		"packSize": 6,
		"quantity": 16,
		"rarity": 9,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have 70% chance to Avoid Elemental Ailments", {
		"nameLong": "Monsters have 70% chance to Avoid Elemental Ailments",
		"nameShort": "elem",
		"nameMod": "of Insulation",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters take (36-40)% reduced Extra Damage from Critical Strikes", {
		"nameLong": "Monsters take (36-40)% reduced Extra Damage from Critical Strikes",
		"nameShort": "kes",
		"nameMod": "of Toughness",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players gain 50% reduced Flask Charges", {
		"nameLong": "Players gain 50% reduced Flask Charges",
		"nameShort": "k c",
		"nameMod": "of Drought",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 30% less Armour |Players have 40% reduced Chance to Block", {
		"nameLong": "Players have 30% less Armour |Players have 40% reduced Chance to Block",
		"nameShort": "rm",
		"nameMod": "of Rust",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters have 50% increased Accuracy Rating |Players have -20% to amount of Suppressed Spell Damage Prevented", {
		"nameLong": "Monsters have 50% increased Accuracy Rating |Players have -20% to amount of Suppressed Spell Damage Prevented",
		"nameShort": "su",
		"nameMod": "of Miring",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 25% less Area of Effect", {
		"nameLong": "Players have 25% less Area of Effect",
		"nameShort": "f ef",
		"nameMod": "of Impotence",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters gain a Frenzy Charge on Hit", {
		"nameLong": "Monsters gain a Frenzy Charge on Hit",
		"nameShort": "a f",
		"nameMod": "of Frenzy",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters gain an Endurance Charge on Hit", {
		"nameLong": "Monsters gain an Endurance Charge on Hit",
		"nameShort": "n an",
		"nameMod": "of Endurance",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters gain a Power Charge on Hit", {
		"nameLong": "Monsters gain a Power Charge on Hit",
		"nameShort": "wer c",
		"nameMod": "of Power",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters Blind on Hit", {
		"nameLong": "Monsters Blind on Hit",
		"nameShort": "bli",
		"nameMod": "of Blinding",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters Maim on Hit with Attacks", {
		"nameLong": "Monsters Maim on Hit with Attacks",
		"nameShort": "att",
		"nameMod": "of Carnage",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters Hinder on Hit with Spells", {
		"nameLong": "Monsters Hinder on Hit with Spells",
		"nameShort": "h s",
		"nameMod": "of Impedance",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Monsters steal Power, Frenzy and Endurance charges on Hit", {
		"nameLong": "Monsters steal Power, Frenzy and Endurance charges on Hit",
		"nameShort": "r,",
		"nameMod": "of Enervation",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 40% less Cooldown Recovery Rate", {
		"nameLong": "Players have 40% less Cooldown Recovery Rate",
		"nameShort": "dow",
		"nameMod": "of Fatigue",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Buffs on Players expire 70% faster", {
		"nameLong": "Buffs on Players expire 70% faster",
		"nameShort": "pi",
		"nameMod": "of Transience",
		"packSize": 4,
		"quantity": 10,
		"rarity": 6,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 60% reduced effect of Non-Curse Auras from Skills", {
		"nameLong": "Players have 60% reduced effect of Non-Curse Auras from Skills",
		"nameShort": "-c",
		"nameMod": "of Doubt",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
	["Players have 25% less Accuracy Rating", {
		"nameLong": "Players have 25% less Accuracy Rating",
		"nameShort": "cu",
		"nameMod": "of Imprecision",
		"packSize": 5,
		"quantity": 13,
		"rarity": 8,
		"parent": "suffix",
		"danger": 0,
		"popularity": 0
	}],
]);