name: Update File

on:
  schedule:
    - cron: '*/5 * * * *' # Run the action every 5 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update File
        uses: actions/github-script@v5
        env:
          NODE_VERSION: '20'  # Set Node.js version to 20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const currentDate = new Date().toString();
            const content = `Last update: ${currentDate}`;

            // Check if the save.js file exists
            if (fs.existsSync('save.js')) {
              // File exists, proceed with writing content
              const c = 'This is the content to be written';
              fs.writeFileSync('save.js', currentDate + ' - ' + c);
              console.log(currentDate + ' - File updated successfully');
            } else {
              // File doesn't exist, create it and write content
              const c = 'New file created and content written';
              fs.writeFileSync('save.js', c);
              console.log('File created and updated successfully');
            }
