name: Economy
on:
  workflow_dispatch:
  schedule:
    - cron:  '* */2 * * *' 
env:
  LEAGUE: Necropolis
  
jobs:
  build:
    name: Update unique items economy files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    # Standard Economy
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueJewel"
        target: Ninja_json/
        filename: Standard_UniqueJewel.json
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueWeapon"
        target: Ninja_json/
        filename: Standard_UniqueWeapon.json
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueArmour"
        target: Ninja_json/
        filename: Standard_UniqueArmour.json
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueAccessory"
        target: Ninja_json/
        filename: Standard_UniqueAccessory.json
        
    # League Economy
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=${{ env.LEAGUE }}&type=UniqueJewel"
        target: Ninja_json/
        filename: "${{ env.LEAGUE }}_UniqueJewel.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=${{ env.LEAGUE }}&type=UniqueWeapon"
        target: Ninja_json/
        filename: "${{ env.LEAGUE }}_UniqueWeapon.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=${{ env.LEAGUE }}&type=UniqueArmour"
        target: Ninja_json/
        filename: "${{ env.LEAGUE }}_UniqueArmour.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=${{ env.LEAGUE }}&type=UniqueAccessory"
        target: Ninja_json/
        filename: "${{ env.LEAGUE }}_UniqueAccessory.json"
        
    # League Hardcore Economy
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Hardcore ${{ env.LEAGUE }}&type=UniqueJewel"
        target: Ninja_json/
        filename: "Hardcore ${{ env.LEAGUE }}_UniqueJewel.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Hardcore ${{ env.LEAGUE }}&type=UniqueWeapon"
        target: Ninja_json/
        filename: "Hardcore ${{ env.LEAGUE }}_UniqueWeapon.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Hardcore ${{ env.LEAGUE }}&type=UniqueArmour"
        target: Ninja_json/
        filename: "Hardcore ${{ env.LEAGUE }}_UniqueArmour.json"
    - uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Hardcore ${{ env.LEAGUE }}&type=UniqueAccessory"
        target: Ninja_json/
        filename: "Hardcore ${{ env.LEAGUE }}_UniqueAccessory.json"

        
    - run: |
       date > generated.txt
       git config user.name github-actions
       git config user.email github-actions@github.com
       git add .
       git commit -m "generated"
       git push
