name: Update File

on:
  push:
    branches:
      - main
      - release/*

  schedule:
    - cron: '*/5 * * * *' # Run the action every 5 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update File
        uses: actions/github-script@v5.1.1
        env:
          NODE_VERSION: '20'  # Set Node.js version to 20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const currentDate = new Date().toString();
            const content = `Last update: ${currentDate}`;
            const path = require('path');
            const filePath = path.join(process.env.GITHUB_WORKSPACE, 'save.js');
            if (fs.existsSync(filePath)) {
              const c = 'This is the content to be written';
              fs.writeFileSync(filePath, currentDate + ' - ' + c);
              console.log(currentDate + ' - File updated successfully');
            } else {
              const c = 'New file created and content written';
              fs.writeFileSync(filePath, c);
              console.log('File created and updated successfully');
            }
