name: JSON to file

on:
  push:
    branches:
      - main

  schedule:
    - cron: '*/5 * * * *' # Run the action every 5 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update File
        uses: devops-actions/json-to-file@v1.0.0
        with:
          json: '{"test": "test"}'
          filename: 'test.json'

      - name: Print confirmation
        run: echo "File updated successfully xyz"
        
