name: Overwrite some file (on specific events)

on:
  # Replace with your desired trigger (e.g., push to main branch)
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *' # Run the action every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Overwrite file and log timestamp
        run: |
          current_date_time=$(date +'%Y-%m-%d %H:%M:%S')
          echo "Aktualna data i czas: $current_date_time"
          echo "$current_date_time - ${{ github.workspace }}/save.js"
          echo "Content of save.js:"
          cat "${{ github.workspace }}/save.js"
