name: Overwrite some file (on specific events)

on:
  # Replace with your desired trigger (e.g., push to main branch)
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Overwrite file and log timestamp
        run: |
          current_date_time=$(date +'%Y-%m-%d %H:%M:%S')
          echo "Aktualna data i czas: $current_date_time" >> /home/runner/work/ugimser.github.io/ugimser.github.io/log.txt
