name: Economy
on:
  workflow_dispatch:
  schedule:
    - cron:  '0/5 * * * *' 
env:
  LEAGUE: Necropolis
  
jobs:
  build:
    name: Update unique items economy files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    # Standard Economy
    - name: Download unique items economy files
      uses: suisei-cn/actions-download-file@v1.3.0
      id: standard_jewel 
      with:
        url: "https://poe.ninja/api/data/itemoverview?league=Standard&type=UniqueJewel"
        target: t/
        filename: eco_Standard_UniqueJewel.json
    - name: Run curl with --user root option
      run: curl --user root


        
    - run: |
       date > generated.txt
       git config user.name github-actions
       git config user.email github-actions@github.com
       git add .
       git commit -m "generated"
       git push
